//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class expert
    {
        public expert()
        {
            this.audits = new HashSet<audit>();
            this.invitations = new HashSet<invitation>();
        }
    
        public int expertId { get; set; }
        public string expert_image { get; set; }
        public int expert_accept_count { get; set; }
        public int user_userId { get; set; }
    
        public virtual ICollection<audit> audits { get; set; }
        public virtual ICollection<invitation> invitations { get; set; }
        public virtual user user { get; set; }
    }
}
