//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class expert
    {
        public expert()
        {
            this.audits = new HashSet<audit>();
            this.invitations = new HashSet<invitation>();
        }
    
        public int expertId { get; set; }
        [Required(ErrorMessage = "*")]
        [RegularExpression(@"^\W[\W\d_]{5-19}$", ErrorMessage = "Please enter valid name.")]
        [Remote("Verify", "CheckExpertNameRegister", ErrorMessage = "user name is registered")]

        public string expert_name { get; set; }

        [Required(ErrorMessage = "*")]
        [RegularExpression(@"^\s*d{11}\s*$", ErrorMessage = "Please enter valid phone no.")]
        public string expert_telephone { get; set; }

        [Required(ErrorMessage = "*")]
        [EmailAddress(ErrorMessage ="email format error")]
        public string expert_mail { get; set; }

        [Required(ErrorMessage = "*")]
        public string expert_address { get; set; }

        public string expert_introduce { get; set; }
        [Required(ErrorMessage = "*")]
        [StringLength(20, MinimumLength = 6, ErrorMessage = "Please enter valid password")]

        public string expert_password { get; set; }
        public byte[] expert_image { get; set; }
        public int expert_accept_count { get; set; }
    
        public virtual ICollection<audit> audits { get; set; }
        public virtual ICollection<invitation> invitations { get; set; }
    }
}
