//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebSiteEntities : DbContext
    {
        public WebSiteEntities()
            : base("name=WebSiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<audit> audits { get; set; }
        public virtual DbSet<bidder> bidders { get; set; }
        public virtual DbSet<bid> bids { get; set; }
        public virtual DbSet<company> companies { get; set; }
        public virtual DbSet<expert> experts { get; set; }
        public virtual DbSet<invitation> invitations { get; set; }
        public virtual DbSet<member> members { get; set; }
        public virtual DbSet<news> news { get; set; }
        public virtual DbSet<purchase> purchases { get; set; }
        public virtual DbSet<team> teams { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<vendor> vendors { get; set; }
    }
}
