//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class team
    {
        public team()
        {
            this.members = new HashSet<member>();
        }
    
        public int teamId { get; set; }
        [Required(ErrorMessage = "*")]
        [RegularExpression(@"^\W[\W\d_]{5-19}$", ErrorMessage = "Please enter valid name.")]

        [Remote("Verify", "CheckTeamNameRegister", ErrorMessage = "user name is registered")]

        public string team_name { get; set; }
        [Required(ErrorMessage = "*")]

        public string team_introduction { get; set; }
        public int createId { get; set; }
    
        public virtual ICollection<member> members { get; set; }
    }
}
