//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Web.Mvc;

namespace WebSite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class user
    {
        public user()
        {
            this.companies = new HashSet<company>();
            this.experts = new HashSet<expert>();
            this.vendors = new HashSet<vendor>();
        }
        
        public int userId { get; set; }
        public string user_type { get; set; }
        [Required(ErrorMessage = "*")]
        [RegularExpression(@"^\d{11}$", ErrorMessage = "Please enter valid phone.")]
        public string user_telephone { get; set; }
        [Required(ErrorMessage = "*")]
        [EmailAddress(ErrorMessage = "Please enter valid email")]
        public string user_mail { get; set; }
      //  [Required(ErrorMessage = "*")]
      //  [RegularExpression(@"^[\w\u4E00-\u9FA5][\u4E00-\u9FA5\w\d_]{0,19}$", ErrorMessage = "Please enter valid name.")]
        [Remote("CheckRegisterNameExist","Verify", AdditionalFields = "user_type", ErrorMessage = "user name is registered")]
        public string user_name { get; set; }
        [Required(ErrorMessage = "*")]

        public string user_address { get; set; }
        [Required(ErrorMessage = "*")]
        public string user_introduction { get; set; }
        [Required(ErrorMessage = "*")]
        [StringLength(20, MinimumLength = 6, ErrorMessage = "Please enter valid password")]
        public string user_password { get; set; }
    
        public virtual ICollection<company> companies { get; set; }
        public virtual ICollection<expert> experts { get; set; }
        public virtual ICollection<vendor> vendors { get; set; }
    }
}

