//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendor
    {
        public vendor()
        {
            this.members = new HashSet<member>();
        }
    
        public int vendorId { get; set; }
        public string vendor_name { get; set; }
        public string vendor_telephone { get; set; }
        public string vendor_mail { get; set; }
        public string vendor_address { get; set; }
        public string vendor_introduction { get; set; }
        public string vendor_password { get; set; }
    
        public virtual ICollection<member> members { get; set; }
    }
}
