//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        public company()
        {
            this.news = new HashSet<news>();
            this.purchases = new HashSet<purchase>();
        }
    
        public int companyId { get; set; }
        public string company_name { get; set; }
        public string company_telephone { get; set; }
        public string company_mail { get; set; }
        public string company_address { get; set; }
        public string company_introduction { get; set; }
        public string company_password { get; set; }
    
        public virtual ICollection<news> news { get; set; }
        public virtual ICollection<purchase> purchases { get; set; }
    }
    public class CompanyDBContext : System.Data.Entity.DbContext
    {
        public System.Data.Entity.DbSet<company> Companies { get; set; }
    }
}
