//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class member
    {
        public int vendorId { get; set; }
        public int teamId { get; set; }
        public int memberId { get; set; }
    
        public virtual team team { get; set; }
        public virtual vendor vendor { get; set; }
    }
}
